// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.20.3
// source: url.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	UrlShorteningService_ShortenUrl_FullMethodName = "/pb.UrlShorteningService/ShortenUrl"
	UrlShorteningService_ExpandUrl_FullMethodName  = "/pb.UrlShorteningService/ExpandUrl"
)

// UrlShorteningServiceClient is the client API for UrlShorteningService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UrlShorteningServiceClient interface {
	ShortenUrl(ctx context.Context, in *ShortenUrlRequest, opts ...grpc.CallOption) (*ShortenUrlResponse, error)
	ExpandUrl(ctx context.Context, in *ExpandUrlRequest, opts ...grpc.CallOption) (*ExpandUrlResponse, error)
}

type urlShorteningServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUrlShorteningServiceClient(cc grpc.ClientConnInterface) UrlShorteningServiceClient {
	return &urlShorteningServiceClient{cc}
}

func (c *urlShorteningServiceClient) ShortenUrl(ctx context.Context, in *ShortenUrlRequest, opts ...grpc.CallOption) (*ShortenUrlResponse, error) {
	out := new(ShortenUrlResponse)
	err := c.cc.Invoke(ctx, UrlShorteningService_ShortenUrl_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *urlShorteningServiceClient) ExpandUrl(ctx context.Context, in *ExpandUrlRequest, opts ...grpc.CallOption) (*ExpandUrlResponse, error) {
	out := new(ExpandUrlResponse)
	err := c.cc.Invoke(ctx, UrlShorteningService_ExpandUrl_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UrlShorteningServiceServer is the server API for UrlShorteningService service.
// All implementations must embed UnimplementedUrlShorteningServiceServer
// for forward compatibility
type UrlShorteningServiceServer interface {
	ShortenUrl(context.Context, *ShortenUrlRequest) (*ShortenUrlResponse, error)
	ExpandUrl(context.Context, *ExpandUrlRequest) (*ExpandUrlResponse, error)
	mustEmbedUnimplementedUrlShorteningServiceServer()
}

// UnimplementedUrlShorteningServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUrlShorteningServiceServer struct {
}

func (UnimplementedUrlShorteningServiceServer) ShortenUrl(context.Context, *ShortenUrlRequest) (*ShortenUrlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShortenUrl not implemented")
}
func (UnimplementedUrlShorteningServiceServer) ExpandUrl(context.Context, *ExpandUrlRequest) (*ExpandUrlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExpandUrl not implemented")
}
func (UnimplementedUrlShorteningServiceServer) mustEmbedUnimplementedUrlShorteningServiceServer() {}

// UnsafeUrlShorteningServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UrlShorteningServiceServer will
// result in compilation errors.
type UnsafeUrlShorteningServiceServer interface {
	mustEmbedUnimplementedUrlShorteningServiceServer()
}

func RegisterUrlShorteningServiceServer(s grpc.ServiceRegistrar, srv UrlShorteningServiceServer) {
	s.RegisterService(&UrlShorteningService_ServiceDesc, srv)
}

func _UrlShorteningService_ShortenUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShortenUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrlShorteningServiceServer).ShortenUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UrlShorteningService_ShortenUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrlShorteningServiceServer).ShortenUrl(ctx, req.(*ShortenUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UrlShorteningService_ExpandUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExpandUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrlShorteningServiceServer).ExpandUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UrlShorteningService_ExpandUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrlShorteningServiceServer).ExpandUrl(ctx, req.(*ExpandUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UrlShorteningService_ServiceDesc is the grpc.ServiceDesc for UrlShorteningService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UrlShorteningService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.UrlShorteningService",
	HandlerType: (*UrlShorteningServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ShortenUrl",
			Handler:    _UrlShorteningService_ShortenUrl_Handler,
		},
		{
			MethodName: "ExpandUrl",
			Handler:    _UrlShorteningService_ExpandUrl_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "url.proto",
}
